apps/mantenedor/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, logout_then_login
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth.views import logout_then_login, PasswordResetForm, PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetDoneView

from .views import index, RegistroUsuario, logout

# app_name = 'mantenedor'

urlpatterns = [
    path('', index, name="index"),
    path('registro/', RegistroUsuario.as_view(), name="registro"),
    path('login/', LoginView.as_view(template_name='mantenedor/login.html'), name="login"),
    path('logout/', logout_then_login, {'login_url': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    # path('logout/', logout, name='logout'),

    path('password-reset', PasswordResetView.as_view(template_name='pswd-reset/password_reset_form.html', email_template_name='pswd-reset/password_reset_email.html'), name="password_reset"),
    path('password-reset/done', PasswordResetDoneView.as_view(template_name='pswd-reset/password_reset_done.html'), name="password_reset_done"),
    path('password-reset/confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(template_name='pswd-reset/password_reset_confirm.html'), name="password_reset_confirm"),
    path('password-reset/complete', PasswordResetCompleteView.as_view(template_name='pswd-reset/password_reset_complete.html'), name="password_reset_complete")
]

apps/rescatados/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import RescatadosList, RescatadosCreate, RescatadosUpdate, RescatadosDelete, RescatadosListAdopcion

app_name = 'rescatados'

urlpatterns = [
    path('listar/', RescatadosList.as_view(), name="rescatados_list"),
    # path('listar/', rescatados_listar, name="rescatados_list"), 
    path('crear/', RescatadosCreate.as_view(), name="rescatados_form"),
    path('editar/<int:pk>', RescatadosUpdate.as_view(), name="rescatados_update"),
    path('borrar/<int:pk>', RescatadosDelete.as_view(), name="rescatados_borrar"),
    path('adopcion', RescatadosListAdopcion.as_view(), name="rescatados_adopcion")
]

misPerris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required, user_passes_test
from rest_framework import routers
from apps.api import views

router = routers.DefaultRouter()
router.register(r'perros', views.PerroViewSet)

urlpatterns = [
    path('', include('pwa.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include(router.urls)),    
    url('', include('social.apps.django_app.urls',namespace='social')),    
    path(r'', include('apps.mantenedor.urls'), name="index"),
    path('admin/', admin.site.urls),    
    path('rescatados/', include('apps.rescatados.urls'), name="recatados")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/mantenedor/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from .validators import validar_rut
# Create your models here.

VIVIENDA_TIPOS = (
    ('Casa con Patio Grande', 'Casa con Patio Grande'),
    ('Casa con Patio Pequeño', 'Casa con Patio Pequeño'),
    ('Casa sin Patio', 'Casa sin Patio'),
    ('Departamento', 'Departamento'),
)

class User(AbstractUser):
    rut = models.CharField(max_length=15, validators=[validar_rut], blank=True, null=True)
    fechaNacimiento = models.DateField(blank=True, null=True)
    region = models.CharField(max_length=80, blank=True, null=True)
    comuna = models.CharField(max_length=50, blank=True, null=True)
    tipoVivienda = models.CharField(max_length=25, blank=True, null=True, choices=VIVIENDA_TIPOS)
    numeroTelefono = models.IntegerField(blank=True, null=True)

apps/mantenedor/forms.py
# from django.contrib.auth.models import User
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator
from .validators import validar_letras, validar_fecha
from django import forms

REGIONES = (
    ('arica','Región de Arica y Parinacota'),
	('tarapaca','Región de Tarapaca'),
	('antofagasta','Región de Antofagasta'),
	('atacama','Región de Atacama'),
	('coquimbo','Región de Coquimbo'),	
	('valparaiso','Región de Valparaiso'),
	('ohiggins','Región del Libertador General Bdo. OHiggins'),
	('maule','Región del Maule'),
	('biobio','Región de Biobio'),
	('araucania','Región de La Araucania'),
	('rios','Región de Los Rios'),
	('lagos','Región de Los Lagos'),
	('aisen','Región Aisén del Gral. Carlos Ibáñez del Campo'),
	('magallanes','Región de Magallanes y de la Antártica Chilena'),
	('metropolitana','Región Metropolitana de Santiago'),
)

class RegistroForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegistroForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['first_name'].validators = [validar_letras]
        self.fields['last_name'].required = True
        self.fields['email'].required = True
        self.fields['region'].required = True
        self.fields['comuna'].required = True
        self.fields['rut'].required = True
        self.fields['numeroTelefono'].required = True
        self.fields['fechaNacimiento'].required = True
        self.fields['fechaNacimiento'].validators = [validar_fecha]
        self.fields['tipoVivienda'].required = True
        self.fields['password1'].widget = forms.TextInput(attrs={'class':'form-control','type':'password'})
        self.fields['password2'].widget = forms.TextInput(attrs={'class':'form-control','type':'password'})        

    class Meta:
        model = User
        fields = (
            'username',
            'rut',
            'first_name',
            'last_name',
            'last_name',
            'fechaNacimiento',
            'email',
            'numeroTelefono',            
            'region',
            'comuna',            
            'tipoVivienda',
            'password1',
            'password2'                                 
        )
        widgets = {
            'rut': forms.TextInput(attrs={'class':'form-control','onkeypress':'return validarRut(event)'}),
            'first_name': forms.TextInput(attrs={'class':'form-control','onkeypress':'return validarLetras(event)'}),
            'last_name': forms.TextInput(attrs={'class':'form-control','onkeypress':'return validarLetras(event)'}),
            'fechaNacimiento': forms.DateInput(attrs={'class':'form-control','type': 'date','max': '31-01-2018'}),
            'numeroTelefono': forms.TextInput(attrs={'class':'form-control','onkeypress':'return validarNumeros(event)'}),
            'region': forms.Select(choices=REGIONES ,attrs={'id':'id_cmbRegiones','class':'custom-select'}),            
            'comuna': forms.Select(attrs={'id':'id_cmbComunas','class':'custom-select'}),
            'tipoVivienda': forms.Select(attrs={'class':'custom-select'}),    
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.TextInput(attrs={'class':'form-control','type':'email'})
        }
        labels = {
            'numeroTelefono': 'Numero de teléfono',
            'tipoVivienda': 'Tipo de vivienda',
            'fechaNacimiento': 'Fecha de nacimiento',
        }

apps/mantenedor/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# from django.contrib.auth.models import User
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import RegistroForm
from django.contrib.auth import logout

from apps.rescatados.models import Perro

# Create your views here.

def index(request):   
    perro = Perro.objects.all()
    context = {'perros':perro} 
    return render(request, 'mantenedor/index.html', context)

# def registro(request):      
#     return render(request, 'mantenedor/registro.html')

def passwordReset(request):
    return render(request, 'mantenedor/password_reset.html')

class RegistroUsuario(CreateView):
    model = User
    template_name = "mantenedor/registro.html"
    form_class = RegistroForm
    success_url = reverse_lazy('login')

def logOut(request):
    logout(request)
    return redirect('/')

apps/mantenedor/templates/base/base.html
{% load pwa %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    {% progressive_web_app_meta %}
    <!-- Titulo -->
    <title>Mis Perris - {% block title %} Title {% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Estilos -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    {% block head %}
    {% endblock %}

</head>
<body>
<div class="content">      
    {% block navbar %}
    <!-- Cabezera -->
    <nav id="navbar">
        <div id="navbar-logo">
            <img src="{% static 'images/img/logo.png' %}" alt="logo">
        </div>
        <div id="nav">
            <ul>            
                <li class="nav-item"><a href="{% url 'index' %}">inicio</a></li>
                <li class="nav-item"><a href="#">servicios</a></li>
                <li class="nav-item"><a href="#">quiénes somos</a></li>
                <li class="nav-item"><a href="#">contáctanos</a></li>

                {% if not user.is_authenticated %}        
                <li class="nav-item"><a href="{% url 'registro' %}">registrarse</a></li>
                <li class="nav-item"><a href="{% url 'login' %}">iniciar sesión</a></li>
                <li class="nav-item"><a  href="{% url 'social:begin' 'facebook' %}">Facebook Login</a></li>
                {% endif %}
                
                {% if user.is_authenticated %}
                {% if user.is_superuser %}
                <li class="nav-item"><a style="color: red;" href="{% url 'rescatados:rescatados_list' %}">Rescatados</a></li>
                {% endif %}
                <li class="nav-item"><a style="color: red;" href="{% url 'rescatados:rescatados_adopcion' %}">Adopción!</a></li>
                <li class="nav-item"><a href="{% url 'logout' %}">Cerrar sesión</a></li>
                <span class="ml-md-5" style="color: blue;"><strong>Usuario: {{ user.get_username }}</strong></span>
                {% endif %}                
            </ul>
        </div>                                 
    </nav>
    {% endblock %}

    {% block header %}
    <!-- Carrusel -->
    {% endblock %}

    {% block contactinfo %}
    <!-- Infrmacion de contacto -->
    <div id="contact">
            <div id="p1">+ 56 9 98765431</div>
            <div id="p2">Rescate y adopción de perros callejeros</div>
            <div id="p3">
                <ul>
                    <li><div class="social"><img height="16" src="{% static 'images/icons/facebook-f-brands.svg' %}" alt="facebook"></div></li>
                    <li><div class="social"><img height="16" src="{% static 'images/icons/google-plus-g-brands.svg' %}" alt="google"></div></li>
                    <li><div class="social"><img height="16" src="{% static 'images/icons/instagram-brands.svg' %}" alt="instagram"></div></li>
                    <li><div class="social"><img height="16" src="{% static 'images/icons/envelope-solid.svg' %}" alt="email"></div></li>                    
                </ul>
            </div>
        </div>    
    {% endblock %}

    {% block content %}   
    {% endblock %}

    {% block footer %}
    <!-- Pie de página -->
    <footer id="footer" class="navbar navbar-fixed-bottom">
        <p>Desarollo Web y Mobile - Ariel Chácon, Nicolás Leporati</p>
    </footer>
    {% endblock %}    
</div>

    <!-- Scripts -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block extrajs %}
    {% endblock %}

</body>
</html>