apps/rescatados/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import RescatadosList, RescatadosCreate, RescatadosUpdate, RescatadosDelete, RescatadosListAdopcion

app_name = 'rescatados'

urlpatterns = [
    path('listar/', RescatadosList.as_view(), name="rescatados_list"),
    # path('listar/', rescatados_listar, name="rescatados_list"), 
    path('crear/', RescatadosCreate.as_view(), name="rescatados_form"),
    path('editar/<int:pk>', RescatadosUpdate.as_view(), name="rescatados_update"),
    path('borrar/<int:pk>', RescatadosDelete.as_view(), name="rescatados_borrar"),
    path('adopcion', RescatadosListAdopcion.as_view(), name="rescatados_adopcion")
]

misPerris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required, user_passes_test
from rest_framework import routers
from apps.api import views

router = routers.DefaultRouter()
router.register(r'perros', views.PerroViewSet)

urlpatterns = [
    path('', include('pwa.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include(router.urls)),    
    url('', include('social.apps.django_app.urls',namespace='social')),    
    path(r'', include('apps.mantenedor.urls'), name="index"),
    path('admin/', admin.site.urls),    
    path('rescatados/', include('apps.rescatados.urls'), name="recatados")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/rescatados/models.py
from django.db import models
# from django.forms import ModelForm

# Create your models here.

PERRO_ESTADOS = (
    ('Disponible', 'Disponible'),
    ('Rescatado', 'Rescatado'),
    ('Adoptado', 'Adoptado'),
)

class Perro (models.Model):

    fotografia = models.ImageField(upload_to='rescatados')
    nombre = models.CharField(max_length=50)
    razaPredominante = models.CharField(max_length=50)
    descripcion = models.TextField(max_length=150)
    estado = models.CharField(max_length=50, choices=PERRO_ESTADOS)

    def __unicode__(self,):
        return str(self.fotografia)

apps/rescatados/forms.py
from .models import Perro
from django import forms

class RescatadosForm(forms.ModelForm):
    

    class Meta:
        model = Perro
        fields = (
            'fotografia',
            'nombre',
            'razaPredominante',
            'descripcion',
            'estado'
        )
        labels = {
            'fotografia':'Fotografia',
            'nombre':'Nombre Mascota',
            'razaPredominante':'Raza',
            'descripcion':'Descripcion',
            'estado':'Estado'
        }
        widgets = {
            # 'fotografia':forms.FileInput(attrs={'class':'form-control','type':'file'}),
            'nombre':forms.TextInput(attrs={'class':'form-control'}),
            'razaPredominante':forms.TextInput(attrs={'class':'form-control'}),
            'descripcion':forms.TextInput(attrs={'class':'form-control'}),
            'estado':forms.Select(choices="PERRO_ESTADOS", attrs={'class':'form-control'}),
        }

    

apps/rescatados/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import UserPassesTestMixin, AccessMixin, LoginRequiredMixin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Perro
from .forms import RescatadosForm
# Create your views here.

class UserLoginSuperuser(UserPassesTestMixin):
    login_url = 'login'
    redirect_field_name = 'next'

    def test_func(self):
        return self.request.user.is_superuser
        
    # def handle_no_permission(self):
    #     return redirect('index')


class RescatadosList (UserLoginSuperuser, ListView):                    
    model = Perro
    template_name = 'rescatados/rescatados_list.html'


class RescatadosCreate (UserLoginSuperuser, CreateView):
    model = Perro
    form_class = RescatadosForm
    template_name = 'rescatados/rescatados_form.html'
    success_url = reverse_lazy('rescatados:rescatados_list')


class RescatadosUpdate(UserLoginSuperuser, UpdateView):
    model = Perro
    form_class = RescatadosForm
    template_name = 'rescatados/rescatados_form.html'
    success_url = reverse_lazy('rescatados:rescatados_list')


class RescatadosDelete(UserLoginSuperuser, DeleteView):
    model = Perro
    template_name = 'rescatados/rescatados_borrar.html'
    success_url = reverse_lazy('rescatados:rescatados_list')


class RescatadosListAdopcion(ListView):
    model = Perro
    queryset = Perro.objects.filter(estado="Disponible")
    template_name = 'rescatados/rescatados_adopcion.html'

apps/rescatados/templates/rescatados/rescatados_adopcion.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="container">
<br>
<!-- Galeria -->
{% if object_list %}
<h1 class="bg-green pt-2 pb-4 display-3 text-center">¡Perros en adopción!</h1>
<div class="bg-green mt-3 mb-5 pb-4">        
    <div id="galeria" class="bg-clear">        
        <!-- Imagenes -->
        {% if object_list %}
        {% for perro in object_list %}
        <div class="item-galeria mb-3 all 1">
            <img class="img-fluid" src=../static/images/{{perro.fotografia}} alt="{{ perro.nombre }}">
            <div class="caption">
                <h5 class="mb-0">{{ perro.nombre }}</h5>
                <i>{{ perro.estado }}</i>
                <p>{{ perro.descripcion }}</p>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>
{% else  %}
<h1>Aun no tenemos perros en adopción</h1>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endif  %}
</div>
{% endblock %}

apps/rescatados/templates/rescatados/rescatados_borrar.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block content %}

<body>

<div class="container mb-3 mt-3">

<form method="POST">{% csrf_token %}

    <div>
       
    <h3>¿Desea eliminar el registro de {{object.nombre}}?</h3><br>
    <button class = "btn btn-danger" type="submit">Si</button>
    <a class= "btn btn-default" href="{% url 'rescatados:rescatados_list' %}">Cancelar</a> 
    
    </div>

</form>
<br><br><br><br><br><br><br><br><br><br><br><br>

</div>

</body>

{% endblock %}

apps/rescatados/templates/rescatados/rescatados_form.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}Registro de perro{% endblock %}

{% block content %}
<div class="container mt-3 pb-3">
    <div class="col-md-5">
    <h1>Registrar perro</h1>
    <form id="formulario" method="POST" enctype= "multipart/form-data" >{% csrf_token %}
        {% csrf_token %}
        <!-- {{ form.as_p }} -->

        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.name}}">{{ field.label_tag }}</label><br>            
            {{ field }}
            <div class="bg-danger mt-1">{{ field.errors }}</div>
        </div>
        {% endfor %}
        
        
        <input type="submit" value="Grabar" class="btn btn-success">
    
    </form>
</div>
</div>
{% endblock %}

apps/rescatados/templates/rescatados/rescatados_list.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="container">
<h1 class="display-3">Rescatados</h1>
<hr>
<a class="btn" role="button" href="{% url 'rescatados:rescatados_form' %}">Agregar</a>
<hr>

{% if not object_list %}
<h1>No hay registro de perros</h1>
<br><br><br><br><br><br><br><br>
{% else %}
<table class="table table-bordered">
    <thead>
         <tr>
             <td>Fotografia</td>
             <td>Nombre</td>
             <td>Raza</td>
             <td>Descripcion</td>
             <td>Estado</td>
             <td>Acciones</td>
         </tr>
    </thead>
    <tbody>  
         {% for perro in object_list %}      
         <tr>
             <td><img src= ../../static/images/{{ perro.fotografia }} style="width: 100px;"/> </td>
             <td>{{ perro.nombre }}</td>
             <td>{{ perro.razaPredominante }}</td>
             <td>{{ perro.descripcion }}</td>
             <td>{{ perro.estado }}</td>
             <td>
                 <a class="btn btn-primary" href="{% url 'rescatados:rescatados_update' perro.id%}">Editar</a>
                 <a class="btn btn-danger" href="{% url 'rescatados:rescatados_borrar' perro.id%}">Eliminar</a>
             </td>
             
         </tr>
         {% endfor %}                                
    </tbody>
</table>
{% endif %}

</div>

{% endblock %}